name: Deploy

on: 
  push: 
    branches: deploy

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - run: npm install
      - run: npm run build


      - name: Deploy with gh-pages
        run: |
          echo test(3)
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_TOKEN}
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}